### Create new exchange request
POST {{url}}/api/exchange-requests
Content-Type: application/json
Accept: application/json
Authorization: Basic {{username}} {{password}}

{
    "from_currency_id": 1,
    "to_currency_id": 3,
    "amount_from": "100",
    "amount_to": "500"
}
